# Generated by Django 4.2.1 on 2023-11-11 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=255)),
                ('house_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tsj.address')),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tsj.address')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tsj.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('work_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tsj.workposition')),
            ],
        ),
        migrations.CreateModel(
            name='TsjRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tsj.address')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tsj.resident')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tsj.status')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tsj.worktype')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tsj.worker')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tsj.address')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tsj.apartment')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tsj.resident')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tsj.status')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tsj.worktype')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tsj.worker')),
            ],
        ),
    ]
