# Generated by Django 4.2.1 on 2023-11-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='work_types',
            field=models.ManyToManyField(to='tsj.worktype'),
        ),
    ]
