# Generated by Django 4.2.1 on 2023-11-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsj', '0002_worker_work_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
