# Generated by Django 4.2.1 on 2023-11-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsj', '0003_alter_worker_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='work_types',
        ),
        migrations.AddField(
            model_name='worktype',
            name='work_position',
            field=models.ManyToManyField(to='tsj.workposition'),
        ),
    ]
