# Generated by Django 4.2.1 on 2023-11-12 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsj', '0004_remove_worker_work_types_worktype_work_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktype',
            name='work_position',
        ),
        migrations.AddField(
            model_name='worktype',
            name='work_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tsj.workposition'),
        ),
    ]
