# Generated by Django 4.2.1 on 2023-11-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsj', '0005_remove_worktype_work_position_worktype_work_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='address',
        ),
    ]
