# Generated by Django 4.2.1 on 2023-11-14 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsj', '0007_request_requesttype_remove_tsjrequest_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktype',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tsj.requesttype', verbose_name='Тип заявки'),
        ),
    ]
