# Generated by Django 4.2.1 on 2023-11-16 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsj', '0009_alter_address_options_alter_apartment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tsj.apartment', verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='request',
            name='resident',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='tsj.resident', verbose_name='Житель'),
        ),
    ]
