# Generated by Django 4.2.1 on 2023-11-19 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsj', '0010_alter_request_apartment_alter_request_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttype',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='tsj.address', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='request',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tsj.resident', verbose_name='Житель'),
        ),
    ]
