# Generated by Django 4.2.1 on 2023-11-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsj', '0012_alter_requesttype_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resident',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='workposition',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
