# Generated by Django 4.2.1 on 2023-11-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsj', '0013_alter_resident_options_workposition_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workposition',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
